apiVersion: apps/v1
kind: Deployment
metadata:
  name: seatservice
  labels:
    app: seatservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seatservice
  template:
    metadata:
      labels:
        app: seatservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "seatservice"
        dapr.io/app-port: "50051"
        dapr.io/log-level: "info"
        dapr.io/app-protocol: "grpc"
    spec:
      containers:
        - name: seatservice
          image: ghcr.io/softwaredefinedvehicle/swdc-os-vehicleapi/seat_service:v0.14.0
          imagePullPolicy: IfNotPresent
          ports:
          - name: default
            containerPort: 50051
            protocol: TCP
          env:
          - name: VEHICLEDATABROKER_DAPR_APP_ID
            value: vehicledatabroker
          - name: PORT
            value: "50051"
      imagePullSecrets:
        - name: ghcr-io
---
apiVersion: v1
kind: Service
metadata:
  name: seatservice-nodeport
spec:
  type: NodePort
  selector:
    app: seatservice
  ports:
    - port: 50051
      targetPort: 50051
      nodePort: 30051
