# /********************************************************************************
# * Copyright (c) 2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * https://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: Build SDV application container images
on:
  pull_request:
  workflow_dispatch:

jobs:
  build-container-images:
    name: Build Container Images
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update apt
      run: sudo apt-get update -y

    - name: Install tools
      run: sudo apt-get install -y --no-install-recommends socat file gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint xterm python3-subunit mesa-common-dev zstd liblz4-tool tmux mc skopeo fdisk ruby-full jq libvirt-clients libvirt-daemon-system qemu-system-x86 qemu-system-arm qemu-kvm squashfs-tools rauc python3-newt ca-certificates curl gnupg lsb-release

    - name: Install kas
      run: sudo pip3 install kas

    - name: Cache Downloads
      id: cache-downloads
      uses: actions/cache@v3
      with:
        path: build/downloads
        key: bb-downloads

    - name: Cache SState
      id: cache-sstate
      uses: actions/cache@v3
      with:
        path: build/sstate-cache
        key: bb-sstate-cache

    - name: Cache Local
      id: cache-local
      uses: actions/cache@v3
      with:
        path: build/cache
        key: bb-cache-local

    - name: Build container images for QEMU x86-64
      run: kas build kas/.config-kirkstone.yaml:kas/mirrors.yaml --target packagegroup-sdv-container-images

    - name: Upload QEMU x86-64 images
      uses: actions/upload-artifact@v3
      with:
        name: AppContainerImages_QEMUx86-64
        if-no-files-found: error
        path: build/tmp/deploy/images/qemux86-64/*qemux86-64-oci.tar

    - name: Build container images for Raspberry Pi 4
      run: kas build kas/.config-kirkstone-rpi4.yaml:kas/mirrors.yaml --target packagegroup-sdv-container-images

    - name: Upload Raspberry Pi 4 (64bit) images
      uses: actions/upload-artifact@v3
      with:
        name: AppContainerImages_RaspberryPi4-64
        if-no-files-found: error
        path: build/tmp/deploy/images/raspberrypi4-64/*raspberrypi4-64-oci.tar
